BORDER_SIZE: 24

VAULT:
  MINY: 70
  MAXY: 320
  BLUE:
    MINX: 490
    MAXX: 510
    MINZ: 490
    MAXZ: 510
  RED:
    MINX: -510
    MAXX: -490
    MINZ: -510
    MAXZ: -490

DATABASE:
  URL: jdbc:mysql://localhost:3306/netheritewars
  USER: root
  PASSWORD: 9sjxq#CxJUMj8hu3Nfv576c$D*^NjLvjak5wUYU3gBuowFHsi4rCGC@49YdDhkueyndtcbKa5pAzERzUSwGpF*oqRimhZXtyf$2X@zeWjPA2ex9$#$yJ%aJ4TVeQJdwW