name: NetheriteWars
version: '${project.version}'
main: dev.dercoderjo.netheritewars.NetheriteWars
api-version: '1.21'
author: dercoderjo
commands:
  kill:
    description: Kills yourself
    usage: /kill
    default: true
  peace:
    description: Disables fishting with other players
    usage: /peace
    default: true
    aliases:
      - frieden
  nopeace:
    description: Enables fighting with other players (Disables /peace)
    usage: /nopeace
    default: true
    aliases:
      - keinfrieden
      - unpeace
  gift:
    description: Sets a netherite-gift.
    usage: /gift <Number 1-175> [standard | blocks | random]
    default: true
  battleroyale:
    description: Battle Royale
    usage: /battleroyale <prepare | start | pause | unpause | addtime <Zahl><s | m | h> | end>
    default: true
  addnetherite:
    description: Add Netherite Blocks to Team
    usage: /addnetherite <Blau | Rot> <Number >0>
    default: true
  removenetherite:
    description: Remove Netherite Blocks from a Team
    usage: /removenetherite Blau | Rot> <Number >0>
    default: true
    aliases:
      - remnetherite
  stats:
    description: Toggle the Teamnetherite Scoreboard
    usage: /stats
    default: true
  help:
    description: Show the help menu
    usage: /help
    default: true
