name: NetheriteWars
version: '0.0.1-1.21'
main: dev.dercoderjo.netheritewars.NetheriteWars
api-version: '1.21'
author: dercoderjo
commands:
  kill:
    description: Kills yourself
    usage: /kill
    default: true
  peace:
    description: Peace mode
    usage: /peace
    default: true
    aliases:
      - frieden
  nopeace:
    description: No Peace mode
    usage: /nopeace
    default: true
    aliases:
      - keinfrieden
      - unpeace
  gift:
    description: Sets a netherite-gift.
    usage: /gift <anzahl> <typ>
    default: true
  battleroyale:
    description: Battle Royale
    usage: /battleroyale
    default: true
  addnetherite:
    description: Add Netherite Blocks to Team
    usage: /addnetherite <team> <anzahl>
    default: true
  removenetherite:
    description: Remove Netherite Blocks from a Team
    usage: /removenetherite <team> <anzahl>
    default: true
    aliases:
      - remnetherite
  stats:
    description: Toggle the Teamnetherite Scoreboard
    usage: /stats
    default: true
